### ISSUE TITLE
As a user, I want to be able to create threads, in order to start a debate or discussion

### ISSUE THREAD

**Issue by RocknRollGlue** [DMU-4-sem-2015/DMU-4-sem-php-project-Repository#11]

**Comment by Lisesoee** [comment]
Created the html skeleton and the php file for adding the functionality that is used when submitting the information in the form (containing name of post and text).
Now database connection and functionality is needed to be able to actually post a thread.

**Comment by Lisesoee** [comment]
We are now posting. Though with hardcoded category and userID
